networks:
  arp_lab:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24

# build:
#   context: ./Tests/test1/server
#   dockerfile: Dockerfile
services:
  ftp_server:
    image: fauria/vsftpd
    container_name: ftp_server
    restart: unless-stopped
    networks:
      arp_lab:
        ipv4_address: 172.20.0.10
    environment:
      FTP_USER: labuser
      FTP_PASS: 42isTheAnswer
      PASV_ADDRESS: 172.20.0.10

  client:
    container_name: ftp_client
    restart: unless-stopped
    networks:
      arp_lab:
        ipv4_address: 172.20.0.20
    build:
      context: ./Tests/test1/client
      dockerfile: Dockerfile
    depends_on:
      - ftp_server
    environment:
      FTP_HOST: ftp_server
      FTP_PORT: "21"
      FTP_USER: labuser
      FTP_PASS: 42isTheAnswer
    command: >
      sh -c "until nc -z $${FTP_HOST} $${FTP_PORT}; do
      echo 'Waiting for FTP server...'; sleep 2; done;
      echo 'FTP server is reachable at' $${FTP_HOST}:$${FTP_PORT};
      sleep infinity"

  attacker:
    container_name: attacker
    networks:
      arp_lab:
        ipv4_address: 172.20.0.99
    build: .
    cap_add:
      - NET_ADMIN    # RAW_SOCKET access
      - NET_RAW